### ISSUE TITLE
Error on python3

### ISSUE THREAD

**Issue by bpedersen2** [JBKahn/rednose#1]
```
Traceback (most recent call last):
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/jenkins/workspace/NicosRunTestPy3/custom/resi/test_resi/test_proxy.py", line 14, in setup_module
    raise SkipTest('RESI specific Nonius libs not present')
unittest.case.SkipTest: RESI specific Nonius libs not present

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/pythonvenvs/nicos-py3-new/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python3.4/unittest/main.py", line 93, in __init__
    self.runTests()
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/core.py", line 62, in run
    test(result)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 225, in run
    test(orig)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/suite.py", line 215, in run
    result.addError(self, self._exc_info())
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/nose/proxy.py", line 132, in addError
    self.result.addError(self.test, self._prepareErr(err))
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/rednose.py", line 251, in addError
    self._generate_and_add_test_report(error, test, err)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/rednose.py", line 240, in _generate_and_add_test_report
    report = self._report_test(len(self.test_failures_and_exceptions), type_, test, err)
  File "/home/jenkins/pythonvenvs/nicos-py3-new/lib/python3.4/site-packages/rednose.py", line 295, in _report_test
    test_id = self.ids.get(test.address(), self.total)
AttributeError: 'ContextSuite' object has no attribute 'address'
```

**Comment by JBKahn** [comment]
I have a basic python 3 smoke test that runs the module, but it's on python 3.5, I'll take a look at 3.4 tonight, maybe they changed something in 3.4 and reverted in 3.5

**Comment by JBKahn** [comment]
On the chance it has to do with cross module compatibility, what other modules/args are you using with nose?

**Comment by bpedersen2** [comment]
We are running with the follwoing args/packages: --with-id --with-coverage 

using nose-xcover and xunit output.

**Comment by bpedersen2** [comment]
And maybe relevant as well: SkipTest is raised from the setupModule function:
def setup_module():
    if residevice.position is None:
        raise SkipTest('RESI specific Nonius libs not present')

**Comment by JBKahn** [comment]
Gotcha, when it's raised in setup_module the `test` element that fails is not the same as an individual test during a failure in nose, so it lacks the ability to make that call. I'll catch that exception for now and bump tonight.

**Comment by JBKahn** [comment]
That should be solved, try 1.1.0

**Comment by JBKahn** [comment]
I'm going to close this for now, reopen if you still have trouble.

**Comment by bpedersen2** [comment]
It is working fine, sorry for not reporting back earlier. 
Thanks for the quick fix.

**Comment by JBKahn** [comment]
np
